version: '3.8'

services:
  todolist-api:
    build: .
    container_name: todolist-api
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - DATA_DIR=/data
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
